### ISSUE TITLE
Adresses API consumption

### ISSUE THREAD

**Issue by diegoaguilar** [jbdemonte/angular-google-maps-native#10]
I'd like to obtain some sort of adress search autocomplete, I want to only use [https://github.com/jbdemonte/angular-google-maps-native](angular-google-maps-native) and probably some "autocomplete only" angular directive but that's it. I don't want to include something like [https://github.com/wpalahnuk/ngAutocomplete](ngAutocomplete) as that would mean including Google API twice.

Any ways to achieve this? Maybe it could be added as a feature improvement?

**Comment by jbdemonte** [comment]
Google API load is disabled if already loaded since issue #4 
The autocomplete is not planned for now (not enough time currently, sorry)
