### ISSUE TITLE
Problem adding coordinates and paths from scope variable

### ISSUE THREAD

**Issue by pankas87** [jbdemonte/angular-google-maps-native#12]
I have a small app that requests some segments from a REST API.

The response is an array of objects, each with a points attribute, an array of points to display a polyline, which I display like this in my template

```
<gm-map options="{center: [-33.4378305,-70.65044920000003], zoom: 12, mapTypeId: google.maps.MapTypeId.ROADMAP};" gm-then="map_loaded(map)" ng-if="showMap">
  <gm-polyline ng-if="segments.length > 0" ng-repeat="segment in segments"
  options="{clickable: true, strokeColor: '#FF0000', strokeOpacity: 1.0, strokeWeight: 2, path: segment.points}"
  on-mousedown="polyline.setOptions({strokeColor: '#0000FF'})"
  on-mouseup="polyline.setOptions({strokeColor: '#FF0000'})"
  ></gm-polyline>
</gm-map>
```

I get this error in the console

Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!

I saw the FAQ in the library website, it says that you must use constant values instead of variables to set paths and coordinates, is there any way to make it work with scope variables without getting and error?

**Comment by jbdemonte** [comment]
https://docs.angularjs.org/error/$rootScope/infdig
Have you tried to put your path out of the options argument, directly in path="segment.points", depending on the stucture, it may fix

**Comment by pankas87** [comment]
When I do that I get a "missing path" error

**Comment by jbdemonte** [comment]
Provide a jsfiddle please
