### ISSUE TITLE
Support infowindow events?

### ISSUE THREAD

**Issue by nanoo-k** [jbdemonte/angular-google-maps-native#15]
I specifically want to use the `domready` event for the infowindow (defined in link below). Judging by the existence of `infoWindow.gm_bindings_.domready`, it looks like you may already let developers bind to this event but I'm not sure how to do it and I don't find an explanation on the infowindow page of your documentation. Could you shed some light on this––am I able to bind to google map events?

https://developers.google.com/maps/documentation/javascript/reference#InfoWindow
http://jbdemonte.github.io/angular-google-maps-native/api-gmInfowindow.html

**Comment by matthieuh** [comment]
You can actually do this with on-domready : 
```
gm-infowindow(
  on-domready ='vm.onDomready()'
)
```

**Comment by nanoo-k** [comment]
That does it! Thanks a lot, now all the other events of open to me too.
