### ISSUE TITLE
Use search instead of the coordinates

### ISSUE THREAD

**Issue by chule143** [jbdemonte/angular-google-maps-native#17]
First of all thanks for the great library :)
I have a question, It's possible to use the search instead the coordinates for center the map?:

this is an example from the Google page: https://developers.google.com/maps/documentation/embed/start?hl=en   (use: "Show the results of a search")
```html
<iframe width="100%" height="400" frameborder="0" style="border:0" ng-src="https://www.google.com/maps/embed/v1/search?q=Japan&key=KEY"></iframe>
```

**Comment by jbdemonte** [comment]
Yes, use [gm-address](http://jbdemonte.github.io/angular-google-maps-native/api-gmAddress.html)

Have a look on the snippet, it does exactly what you're looking for (and add a marker using it center)

**Comment by chule143** [comment]
Thank you @jbdemonte for the answer, works great :)

I have another question, maybe I'm looking wrong but I cannot find the way to make a clickable marker and call an angular function,  http://jbdemonte.github.io/angular-google-maps-native/api-gmMarker.html

**Comment by jbdemonte** [comment]
Using _on_ or _once_ + the event name
Have a look on this [snippet](http://jbdemonte.github.io/angular-google-maps-native/index.html), _on-dragend_ is used
To bind "click", use _on-click_ or _once-click_

**Comment by chule143** [comment]
@jbdemonte works really good, thanks again :) , this is the final code:
```html
<gm-map gm-address="{address: country}" options="{zoom: 6}">
	<gm-marker position='{"lat":it.geo.lat,"lng":it.geo.lng}' ng-repeat="it in locations" on-click="clickLocation(it.id)" on-mouseover="toggleInfo(it.id,true)" on-mouseout="toggleInfo(it.id)">
	<gm-infowindow ng-if="it.show" options="{content: it.name}"></gm-infowindow>
</gm-marker>
```
