### ISSUE TITLE
Draw country border

### ISSUE THREAD

**Issue by chule143** [jbdemonte/angular-google-maps-native#18]
Is there any way to draw a border for the country, paint the inner of the country and zoom like the image also?
https://www.google.com/maps/place/France/@45.8630026,-6.7669772,5z/data=!3m1!4b1!4m2!3m1!1s0xd54a02933785731:0x6bfd3f96c747d9f7

![country](https://cloud.githubusercontent.com/assets/1250071/13853515/6ec231c8-ec3d-11e5-90e9-98b606468548.jpg)

**Comment by jbdemonte** [comment]
No idea sorry, ask on the google support or on stackoverflow
