### ISSUE TITLE
Initializing the library gives a compile error

### ISSUE THREAD

**Issue by andreasi** [jbdemonte/angular-google-maps-native#19]
This is my view

`<gm-map  class="cell" center="location.position" options="{center: [55.514382430060564, -115.056640625], zoom: 4, mapTypeId: google.maps.MapTypeId.ROADMAP}">
        <gm-marker position="location.position" on-click="showMapWindow()">
          <gm-infowindow
               ng-show="showInfoWindow"
               options="{content: '<strong>Location:</strong> {{location.locationName}} <br />
               <strong>Contact:</strong> {{location.contactName}} <br />
               <strong>Lat \& Long:</strong> {{location.position}} <br />
               '}"
               on-closeclick="showMapWindow()"
           >
           </gm-infowindow>
        </gm-marker>
      </gm-map>`

I get the angularjs error

Error: $compile:ctreq
Missing Required Controller
Controller 'gmMap', required by directive 'gmInfowindow', can't be found!
Any idea?Thanks

**Comment by jbdemonte** [comment]
Did you add the GoogleMapsNative module in you requirements (http://jbdemonte.github.io/angular-google-maps-native/quickstart.html) ?

**Comment by andreasi** [comment]
Thank you. 
Yes everything is in place as described in the documentation. GoogleMapsNativestrange in my app.js file as a dependency, gmLibraryProvider in my config function and this is my configuration, gmLibraryProvider.configure({ language: 'en' });. The thing is that the infowindow works just fine. I just get this error in the console. I'm using angularjs version 1.5.0 if that says anything

Thank you

**Comment by jbdemonte** [comment]
I can't reproduce, could you provide an example,
I tested this and didn't get any error log

    <!DOCTYPE html>
    <html ng-app="MyApp">
    <head lang="en">
      <meta charset="UTF-8">
      <link rel="stylesheet" type="text/css" href="assets/style.css">
      <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js"></script>
      <script src="../dist/angular-google-maps-native.min.js"></script>
      <script>
        angular.module('MyApp', ['GoogleMapsNative'])

            .controller('MyCtrl', function ($scope) {
              $scope.location = {
                  position: [55.514382430060564, -115.056640625]
              };

              $scope.showInfoWindow = false;

              $scope.showMapWindow = function () {
                $scope.showInfoWindow = !$scope.showInfoWindow;
              };
            })
        ;

      </script>
    </head>
    <body ng-controller="MyCtrl" ng-init="showInfo=true">
      <gm-map class="cell" center="location.position" options="{center: [55.514382430060564, -115.056640625], zoom: 4, mapTypeId: google.maps.MapTypeId.ROADMAP}">
        <gm-marker position="location.position" on-click="showMapWindow()">
          <gm-infowindow ng-show="showInfoWindow" options="{content: '<strong>Location:</strong> {{location.locationName}} <br /> <strong>Contact:</strong> {{location.contactName}} <br /> <strong>Lat \& Long:</strong> {{location.position}} <br /> '}" on-closeclick="showMapWindow()" > </gm-infowindow>
        </gm-marker>
      </gm-map>


    </body>
    </html>

**Comment by andreasi** [comment]
The code you sent me doesn't show anything on the browser. I believe is because of the missing assets/styles.css dependency. Can you please provide this file too. There is a div created on the DOM after the g-marker element, where if i put width and height for it, then the map shows up but with no marker on it. 
Thanks.
