### ISSUE TITLE
center doesn't accept strings

### ISSUE THREAD

**Issue by jgentes** [jbdemonte/angular-google-maps-native#2]
I was using ngmap prior to trying your module. I like the performance better because of how you've handled loading of the script, but I ran into a few problems I'll submit here.

One is that it would be nice to offer a string such as "Chicago, IL" as the center rather than coordinates. This alleviates the need to do a reverse lookup for coordinates based on a location.

**Comment by jbdemonte** [comment]
You can use gm-address to do this

http://jbdemonte.github.io/angular-google-maps-native/api-gmAddress.html

**Comment by jgentes** [comment]
Ah, sorry - should have read the docs!
