### ISSUE TITLE
Infinite digest for functions

### ISSUE THREAD

**Issue by hmfic** [jbdemonte/angular-google-maps-native#25]
See https://jsfiddle.net/stevegiles/4k6035j7/ for the problem.

If you have a hard coded marker position:
```
<gm-marker options="{position: [39, -120]}">
 </gm-marker>
```
it works fine. However, if you have a position which is computed via function, it creates a infinite digest console error. For example:
```
<gm-marker options="{position: getCoords()}">
      </gm-marker>
```
where the controller simply returns the coordinates:
_$scope.getCoords = function() {
          var mylat = 37;
          var mylong = -121;
          console.log("returning lat and long")
          return [mylat, mylong];
        };_
It does in fact position the marker properly however the infinite digest makes it impossible to use. 

Thanks so much.

**Comment by hmfic** [comment]
Git seems to have thrown away my code snippets. Trying again here:

```
<gm-marker options="{position: [39, -120]}">
      </gm-marker>
      <gm-marker options="{position: getCoords()}">
      </gm-marker>
```

**Comment by jbdemonte** [comment]
normal, you're creating a new array for each call
have a look on this example: https://docs.angularjs.org/error/$rootScope/infdig
