### ISSUE TITLE
gm-map doesn't respect outer div 

### ISSUE THREAD

**Issue by jgentes** [jbdemonte/angular-google-maps-native#3]
I believe this is due to the insertion of the 'absolute' positioning value:

style="position: absolute; top: 0px; right: 0px; bottom: 0px; left: 0px; overflow: hidden; transform: translateZ(0px); background-color: rgb(229, 227, 223);"

I've tried a variety of things, including setting the css on the outer div, as well as on gm-map, but same results - the map expands to the full height of the screen. I previously had two other angular maps modules using the same css, so I don't think that's it.

Even if I specify the width and height directly, it doesn't respect the scale parameters:

`<gm-map style="width: 180px; height: 95px;" options="{center: [37, -122], zoom: 11}"></gm-map>`

**Comment by jbdemonte** [comment]
yes, gm-map requires:  position = relative
If not set, it define it: https://github.com/jbdemonte/angular-google-maps-native/blob/master/dist/angular-google-maps-native.js#L481
