### ISSUE TITLE
An attach a StreetViewPanorama to a Map

### ISSUE THREAD

**Issue by adyba** [jbdemonte/angular-google-maps-native#7]
First of all I do really love this library. Your approach is different but the result is simple, clever, unobtrusive, simple sexy. My only minor question concerns the sample showing an attached StreetViewPanorama (FAQ page). Once I moved "little yellow man" across the ocean into location I know, I have realized both the green arrow and "N" marker on the circle around the pan controller is 180 degrees out of the course. Simply when StreetView is facing the South those markers are pointing to the North and vice versa.

**Comment by adyba** [comment]
My apology. The big G is the problem. Once tested in StreetView (standard Google map) everything worked just fine, thus I suspected the library. I double checked the issue again on several other remote locations where I remember the skyline & orientation. On some locations everything was OK, some (remote small locations) were diverted. The original StreetView must have kinda variable or something to fix the data. It seems this self healing mechanism is not provided to the API. 
So there is a BUG, but not in your code ;)

**Comment by jbdemonte** [comment]
Thanks for this comment  :smile:
