### ISSUE TITLE
Clustering #help_wanted

### ISSUE THREAD

**Issue by adyba** [jbdemonte/angular-google-maps-native#8]
Jean, would you be so nice and give me a hint on clustering (clustered markers)? There are several libraries and my initial trial has just failed miserably. Just preselection of clusterer would be a big help. Thank you in advance.

**Comment by jbdemonte** [comment]
At first, I planned to add this feature, but I didn't had enough time (I did it on gmap3).
For now, I over 100% on another project, but when, I'll have more free time, I'll try

**Comment by godot882** [comment]
Would like to see that too.
